services:
  db:
    image: mysql:8.0.36
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gestion_commerce_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./django-ecommerce
    container_name: django_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./django-ecommerce/.env
    depends_on:
      - db
    volumes:
      - ./django-ecommerce:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./react-ecommerce-site
    container_name: react_frontend
    ports:
       - "5173:80"
    depends_on:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: ecommerce_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data: